### ISSUE TITLE
Use `StringBuilder` instead of `StringBuffer` where used locally

### ISSUE THREAD

**Issue by phax** [javaee/javamail#268]
In some cases - like `InternetHeaders.getHeader(String,String)` - you are using `StringBuffer` internally, which is slightly inefficient.
Using `StringBuilder` would be preferred, as it is not synchronized and therefore quicker.
Of course when using `StringBuffer` somewhere external, this must be considered separately.

P.S. my OCA is only for glassfish - please extend it to this project as well - thx.

**Comment by bshannon** [comment]
The JavaMail code is almost as old as Java.  There's lots of things that could be "modernized", some of which were done for JavaMail 1.6.0.  This hasn't been a priority because the JVM keeps getting better at optimizing this by reducing the overhead of unneeded synchronization.  Still, I'll look at your pull request as soon as I get a chance.

The OCA applies to any Oracle open source project, not just GlassFish, so you're good there.

Thanks.

**Comment by bshannon** [comment]
For some reason I thought I was waiting on an OCA for this.
Obviously I was confused.  Sorry this took so long.
