### ISSUE TITLE
Cannot persist javax.mail.Store to Redis in order to use Store across multiple tomcat instance

### ISSUE THREAD

**Issue by hirrus** [javaee/javamail#297]
I have a simple Java mail application which shows emails from all folders and also able to provide mail compose facility and is divided into front-end  (angular) and back-end (java rest web service). The web service establish connection to my mail server when user log-in. 

javax.mail.Store store = emailSession.getStore("imap");
store.connect(imap3Host, userName, passcode);

And then i want to persist session and store object into Redis, so for any other request for the same user can use the same store and session persisted into Redis. 
Because javax.mail.Store/IMAPStore/Session is not serialized, i am not able to persist it into Redis. However, I have tried to convert it into JSON using JSONSerializer but getting stackOverflow error due to recursion of   DefualtFolder and store dependency.  I have also tried to use Kryo serializer but failed there too.                      
My main concern is i want to re-use the Store and Session objects for each subsequent request to the web service after log-in into the application and don't want to connect to mail server for each request. 
If I have only one tomcat instance then i can save the store and session object into Java.util.map (hashMap) and i can retrieve it from map when get new request received.
Here the problem is i have more than 1 tomcat instance in my production and due to load balancer, the request to web-service can go to any instance where i want to fetch the store or session object from Redis/Redission (distributed memory).

I completely understand the security concern while persisting these object into Redis memory and i think that's why the classes are designed such a way. If we use simple MVC architecture then we can still save these object into web session and re-use it but in case of web-service looks like this is close to impossible.

And, now a days we are using micro-services, spring boot web services and any other latest framework where we need to support Store and Session persistency in order to take Java Mail to next level.

Please suggest me any work around or permanent solution for this.  My sample code is as below;

Properties properties = new Properties();
properties.put("mail.store.protocol", protocol);
 properties.put("mail.imap.host", imap3Host);
 properties.put("mail.imap.port", port);
javax.mail.Session emailSession = javax.mail.Session.getDefaultInstance(properties);
javax.mail.Store store = emailSession.getStore("imap");
store.connect(imap3Host, userName, passcode);

This store object should be persist to Redis, so i can retrieve it and use it without re-connecting to mail server.

**Comment by bshannon** [comment]
The Store object depends on an open socket connection.  There's no way to persist an open
socket connection to Redis (or any database) and be able to reconstitute it on some other
machine.  Mail server connections are stateful.  You need to be able to disconnect from the
mail server and reconnect to the mail server for every request (expensive), or you need to
cache the connection to the mail server so that you can reuse it in the common case.  Still,
when the connection is dropped and reconnected, you have to deal with the fact that the
state of the mailbox may have changed and any other cached information you have about the
mailbox or the messages in it may no longer be valid.

JavaMail gives you access to the information from the mail server that you'll need to handle this,
but how exactly to handle it is a problem for your application.
