### ISSUE TITLE
Need IMAP Sni Support

### ISSUE THREAD

**Issue by nvsnvikram** [javaee/javamail#303]
In some cases, we want to use sun's imap client (IMAPProtocol) to connect to server using a different sni (https://en.wikipedia.org/wiki/Server_Name_Indication). Can we add this support in Protocol?

**Comment by bshannon** [comment]
SNI support requires JDK 1.8, but JavaMail currently only requires JDK 1.7.
SNI support could be added conditionally using reflection, but that's a bit more work.
It's worth considering.

**Comment by bshannon** [comment]
Looking into this further, it appears that JDK 1.7 support SNI, but it doesn't allow you
to customize the server name.  It just uses the server name that you're connecting to.
In your case, what server name are you connecting to and what server name do you
want to supply for SNI?  Isn't your name service mapping the SNI server name to the
correct IP address?

**Comment by nvsnvikram** [comment]
Recently our server has been enhanced to have different flows based on the sni. This requires us to send different SNI to same server for testing. We extensively use the imap reference implementation  for testing. Although, we are working in parallel to get hosts defined with multiple names. It would be nice to configure SNI while connecting to our servers. Let us know if this is possible.

**Comment by bshannon** [comment]
It's not currently possible.  It would be much simpler for you to add host name aliases for
your server so that you can use whatever SNI name you need when connecting to your
server.  The JDK will include an SNI name that matches the host name you use to connect.

If adding a host name alias to your name service is difficult, you should be able to add it
in the local /etc/hosts file on your client machine.

Another more complicated option would be to write your own SSLSocketFactory that
configures the SNI information before returning the SSLSocket.  You could use the
[MailSSLSocketFactory](https://github.com/javaee/javamail/blob/master/mail/src/main/java/com/sun/mail/util/MailSSLSocketFactory.java) code as a starting point.

Let me know if none of those work and I can consider adding this feature in a future release.

**Comment by nvsnvikram** [comment]
Thanks, we are trying out extending MailSSLSocketFactory and trying configuring the server name. I will reopen or create a new one if that doesn't work.
