### ISSUE TITLE
IMAP IDLE. JavaMail uses a cached message count instead real

### ISSUE THREAD

**Issue by DenBond7** [javaee/javamail#319]
Hello. I have some issue when I'm using `ImapFolder.idle();`

I have next code:

```
remoteFolder = (IMAPFolder) store.getFolder(localFolder.getServerFullFolderName()); //It's my INBOX folder
remoteFolder.open(javax.mail.Folder.READ_ONLY);

remoteFolder.addMessageCountListener(this);
remoteFolder.addMessageChangedListener(this);

while (!Thread.interrupted() && isIdlingAvailable()) {
         remoteFolder.idle();
 }
```

and

```
@Override
public void messagesAdded(MessageCountEvent e) {
         Log.d(TAG, "messagesAdded: " + e.getMessages().length);
         loadNewMessages(null, 0, localFolder, e.getMessages());
}
```

Steps for reproducing my issue:

1. start the app
1. run IDLE
1. send a message to the tested email
1. receive callback messagesAdded(MessageCountEvent e)  ---> All looks Ok

![2018-07-18_16-56-08](https://user-images.githubusercontent.com/2863246/42926047-e377e6a6-8b38-11e8-8fa6-b16d8ab965fe.jpg)

5. Move to the web client (Gmail). Delete a few messages from the INBOX folder.
6. send a message to the tested email again. And we are receiving next situation:

![2018-07-18_17-18-41](https://user-images.githubusercontent.com/2863246/42926247-7f2327f0-8b39-11e8-8451-66e4388cc708.jpg)

Is that a normal behavior?

**Comment by bshannon** [comment]
Yes.

Messages can be deleted and expunged on the server, which causes the message numbers for all messages to change.  Unless the client is prepared for that, it can confuse the client, so JavaMail maintains a mapping from what the client thinks the message numbers are to what the message numbers actually are.  If you call the Folder.expunge method, the mapping is reset.

So, I don't think there's an actual problem here.  You should see the added messages when the event is sent.  If you're not seeing the messages you expect to see, please provide more details.

**Comment by DenBond7** [comment]
@bshannon Thank you for your reply. I've found a solution on my side.
